name: Integration tests pipeline

on:
  pull_request:
    branches:
      - 'master'

jobs:
  pipeline:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Run integration tests
        run: |
          dbx deploy integration-test --deployment-file deployment.yaml
          dbx launch integration-test --trace --existing-runs wait
